apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: food-app
data:
  PORT: "4000"
  SERVICE_NAME: "order-service"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "paymentdb"
  DB_USER: "paymentuser"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
